### ISSUE TITLE
iphone4下手机压缩图片不正确，官方DEMO，看截图

### ISSUE THREAD

**Issue by dreamhuo** [think2011/localResizeIMG3#10]
第一张是正常图片，第二张是压缩的问题图片

**Comment by dreamhuo** [comment]
![2057606090623278426](https://cloud.githubusercontent.com/assets/4711168/6552718/fc57fdc8-c683-11e4-90db-8b5cac6f1a07.jpg)

**Comment by think2011** [comment]
@dreamhuo  抱歉，没看明白。

**Comment by dreamhuo** [comment]
![5246676824887876452](https://cloud.githubusercontent.com/assets/4711168/6552772/92d79eb6-c684-11e4-80dd-88c3f803a2d1.jpg)

**Comment by dreamhuo** [comment]
不好意思，网速慢，刚上传了图片

**Comment by think2011** [comment]
@dreamhuo  
恩，有遇见过这个问题，目前没有设备测试，不确定问题出在哪里。
印象中以前拿I4测试的时候是正常的，找个机会调试下。

**Comment by dreamhuo** [comment]
您QQ,多少，可以加下，互相交流吗？

**Comment by dreamhuo** [comment]
631989611

**Comment by think2011** [comment]
@dreamhuo  好哦

**Comment by liuzheng644607** [comment]
在iPhone5 里面也有如此问题。

试了一下解决.
把
                ctx.fillStyle = '#fff';
                ctx.fillRect(0, 0, canvas.width, canvas.height);
                ctx.drawImage(img,0, 0, resize.w, resize.h);

放到 var mpImg = new MegaPixImage(img);
的前面.
由此也有可能出现其他问题，还没有测试过

**Comment by think2011** [comment]
@liuzheng644607  确定是用的线上的demo吗？ 我用的是iphone5 IOS8.1，从没出现过这个问题，请再试一下。

**Comment by liuzheng644607** [comment]
哦测试的系统版本是 IOS7.1.1
![测试](http://liuyaner.qiniudn.com/mmexport1427162436766.jpg)

**Comment by think2011** [comment]
@liuzheng644607 恩，大概知道问题出在哪里了，找个时间修复一下。

**Comment by chengzhuo** [comment]
我这边上传图片也是上面那个样子
https://camo.githubusercontent.com/c4d1620695d2d2d30d0df0e01333caa0a195f2f3/687474703a2f2f6c697579616e65722e71696e6975646e2e636f6d2f6d6d6578706f7274313432373136323433363736362e6a7067

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG3/releases/tag/3.0.13)
