### ISSUE TITLE
部分安卓手机上传图片压缩图片成了白板，如图

### ISSUE THREAD

**Issue by dreamhuo** [think2011/localResizeIMG3#11]
![1629230468986273781](https://cloud.githubusercontent.com/assets/4711168/6552870/8e0f7452-c685-11e4-89fd-9e52ec06e321.jpg)

**Comment by dreamhuo** [comment]
![66435851965098564](https://cloud.githubusercontent.com/assets/4711168/6552877/9b36ec5a-c685-11e4-9aa3-d9fe5b903a02.jpg)

**Comment by think2011** [comment]
已更新
