### ISSUE TITLE
压缩出现比原图片大的问题

### ISSUE THREAD

**Issue by sujy** [think2011/localResizeIMG3#13]
Nexus4 UC浏览器 手机摄像头拍照
原图大小54.77K
压缩后284.74K

想问问为什么会出现这种情况？

**Comment by think2011** [comment]
@sujy 
猜测有2个可优化的原因：
1. 兼容android的jpeg算法生成的文件会很大。
2. UC本身就作了压缩处理。

**Comment by sujy** [comment]
我也是怀疑是UC做过压缩了~
能不能问问为什么兼容android的jpeg算法生产文件会很大？

**Comment by think2011** [comment]
@sujy 
jpeg算法是为了兼容旧版本android无法正确压缩的问题。
那么我会找找兼容性，新版android就不需要压缩算法了，UC处理过压缩的话，那么不压缩也可以。

**Comment by sujy** [comment]
Thx！看完你的博客，感觉好赞！膜拜+努力ing

**Comment by think2011** [comment]
: D
