### ISSUE TITLE
android 手机demo无反应

### ISSUE THREAD

**Issue by liuqingchi** [think2011/localResizeIMG3#14]
我找了四个手机都试了，用手机自带的浏览器，选择照片后，没有反应，显示没有选择照片，qq浏览器正常使用。pc和iphone都正常。

**Comment by think2011** [comment]
我不知道手机型号和系统版本，我也没办法判断问题..

**Comment by liuqingchi** [comment]
好吧，来一个手机huawei 型号S8-701u 版本号S8-701uV100R001C233B003  Android版本4.3 系统版本号Emotion系统1.6 内核版本3.4.0

**Comment by liuqingchi** [comment]
我刚才又找了几个android手机 同样没反应

**Comment by think2011** [comment]
@liuqingchi  我用朋友的小米4自带浏览器测试了一下，能触发拍照和正常上传。


然后我想到2个办法处理这个事情。

1. 找朋友借手机测试....
2. 或者想办法把错误记录下来，可能到时需要你帮忙测试一下。

**Comment by liuqingchi** [comment]
三星手机没问题

**Comment by liuqingchi** [comment]
好像便宜点的，国产的android都不怎么好用，有的第一次选择图片会有两张图片显示，上传到服务器的没有，第二次选择就是空白了

**Comment by liuqingchi** [comment]
我觉得还是浏览器的问题

**Comment by think2011** [comment]
@liuqingchi  低配手机内存较低，android的jpeg处理可能会耗费很多内存，自带浏览器接口不完善也有可能，总之无论如何都得实机调试才行..

对了，demo的上传偶尔是有问题的，只有看见客户端预压出现了，那么后端就没问题的了，因为即使发给后端的就只是一大串字符串而已。

**Comment by liuqingchi** [comment]
问题出在这里 // 调整正确的拍摄方向
                var mpImg = new MegaPixImage(img);
                EXIF.getData(img, function () {
alert(111)这里开始在电脑上是正常的，但是在我的手机自带的浏览器上是 无法执行的。

**Comment by liuqingchi** [comment]
所以我把EXIF.getData(img, function () {}函数去掉了，android自带浏览器就可以正常使用了。不过我没弄明白这个函数具体有什么好处。

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG3/releases/tag/3.0.13)
