### ISSUE TITLE
不用表单如何使用该组件

### ISSUE THREAD

**Issue by fengqiaoguke** [think2011/localResizeIMG3#17]
我想调用原生摄像头(兼容各种版本的系统和低端手机),然后通过js来获取照片路径.请问我这种情况如何使用呢?我按照demo试了一下,还是不行.希望可以直接传入图片地址就能实现压缩

**Comment by think2011** [comment]
是 hybrid app 吗？ 如果是的话，建议直接用原生的方法去做，效率要高很多。

如果不是的话，前端调用摄像头很有限，通过input:file是最好的。

另外除非是本域（跨域）的，否则没办法直接传入图片地址实现压缩。

**Comment by fengqiaoguke** [comment]
因为我是用html5开发,可以兼容ios和安卓,我对这2个平台原生语言也不了解.如果能用你的这个插件就最好了.本域传入图片地址能给个demo吗,非常感激
