### ISSUE TITLE
localResizeIMG3比localResizeIMG上传速度慢

### ISSUE THREAD

**Issue by liuqingchi** [think2011/localResizeIMG3#18]
我用手机上传个2MB的图片经过js处理base64长度为200~300kB左右,在没有wifi的情况下2G比3G慢，4G的手机卡基本上和wifi差不多了，但是还是要30秒左右，服务器端用的php接收的，原以为是网速的问题，但是发现用localResizeIMG比用localResizeIMG3同样的照片，时间节省近一半。我该如何选择

**Comment by think2011** [comment]
lrz 和 lrz3的核心代码是一致的，我也不明白为什么会变慢..

**Comment by liuqingchi** [comment]
刚才又做了一个测试 同一张照片2.69MB，上传到服务器lrz3用了68秒 lrz用了16秒，压缩设置都一样width：500 quality：7     但是服务器接收base64生成的图片尺寸都是500x667，只是大小不一样lrz3是659KB，lrz是105KB，所以我想这个上传速度慢应该和这个压缩大小有很大关系，不知道两个整合一下怎么样。还有用ajax上传不用原生的用jquery至少90kb，加载起来也影响速度

**Comment by think2011** [comment]
用的是Android手机吗？

**Comment by liuqingchi** [comment]
是的

**Comment by liuqingchi** [comment]
苹果手机6plus支持4G速度很快，图片大一点也无所谓了，主要就是android的中端机，像素高，网速不一定高，低端机的话，像素低拍出来就很小，网速最低也是2G的

**Comment by think2011** [comment]
@liuqingchi  怀疑是android的jpeg算法插件的原因。

因为低版本的android无法正确压缩，所以用了新的算法，生成文件很大，例如IOS压缩后是60kb，android算法压缩可能就是200kb。

如果你那边有多个版本的android可以测试的话，希望能帮忙测试一下，我随后调整。

**Comment by think2011** [comment]
@liuqingchi  更新了新版本，依然可以通过 [demo](http://lrz3.herokuapp.com/) 测试，高于4.2的android会采用原生的压缩算法。

如果能正确压缩成jpeg，压缩大小应该和IOS差不多的，测试后请告知我一下。

**Comment by liuqingchi** [comment]
今天又测试了一下，pc和苹果上面2.64MB的图片在设置400，0.7以后 服务器生成的图片大小在100kb以内，这已经符合我的要求了，但是android（上面生成的图片是564KB 还是太大， 至于是不是你说的是jpeg算法的问题，不太清楚，但是localResizeIMG 生成的是105kb 我醉了

**Comment by liuqingchi** [comment]
我测试的是android4.3版本的后来我在js里把限制调了一下，用原生的压缩算法，服务器生成的图片页是500kb左右，

**Comment by liuqingchi** [comment]
刚刚发现一个不知道是不是主要问题的地方，可以把我遇到的问题解决，就是再localResizeIMG3的lrz.js文件里面quality: 7 而在localResizeIMG里面设置quality时是0.7，之所以发现这个问题是因为 results.base64 = encoder.encode(ctx.getImageData(0, 0, canvas.width, canvas.height), that.defaults.quality * 100);这里在quality固定的情况下 两者差了10倍。我开始把100改成10，服务器接收到的图片只有53kb，达到我的要求了，后来考虑到android版本问题还是把quality改成了0.7。不知道我发现的这个是不是造成我的android手机比pc还有苹果手机生成的图片大5倍以上的原因？？？

**Comment by think2011** [comment]
@liuqingchi  是的，问题是出在这里，[发布了新版本](https://github.com/think2011/localResizeIMG3/releases)
