### ISSUE TITLE
关于压缩图片的高度和宽度问题

### ISSUE THREAD

**Issue by liuqingchi** [think2011/localResizeIMG3#19]
我今天检查前几天上传的图片，发现一个对于我来说致命的问题。上传的图片设置固定宽度width为400之后，反着拍的图片(比如像素1280 x 960 的，3264 x 2448的等) 这些照片宽度本来就大，等比例压缩之后，图片的内容还可以看的清。但是正着拍的图片(比如像素720 X 960 2448 x 3264,1944 x 2592等)这些图片像素越大，等比例压缩之后的图片越模糊，尤其是有些图片里面的 打印的文字本来就是瘦体或者数字，模糊的根本无法识别。因为每天都在传照片，也不能width 和height 都设置。
我想问的就是有没有可能智能一点，根据高度宽度判断来调整压缩。因为手机像素不同，拍摄角度不同，像我这种需要图片认证，所以压缩后服务器生成的图片必须能看清上面的文字的，不然压缩后上传的图片没有任何意义。

**Comment by think2011** [comment]
我猜上传的是证件类的图片，之前做的一个项目是这样的需求，我把图片压缩的宽度设置为1024来解决的。

如果需要实现你想要的是效果，你理想的API应该是怎么写的？

**Comment by liuqingchi** [comment]
我觉得这个需要考虑手机的像素问题，因为图片像素越高生成的图片越大，相对应的压缩时必须宽度或者高度必须够大才可以看的清楚些，反之那些像素低的手机拍出来的照片本来就不大，压缩时宽度或者高度小一些还是可以看得清楚，所以我觉得应该根据手机像素来预设置一下 默认设置的width或者height的值
 /**
         * 获得图片的缩放尺寸
         * @param img
         * @returns {{w: (Number), h: (Number)}}
         */
        resize: function(img) {
			var img_w=img.width;
			var img_h=img.height;
			if(img_w>=img_h){
				this.defaults.width = 600;
			}else{
				if(img_h<=800){
					this.defaults.width=img_w;
				}else{
					if(img_w<720){
						this.defaults.width=img_w;
					}else{
						this.defaults.width = 700;
					}
				}
			}

**Comment by liuqingchi** [comment]
我现在只能这样来设置上传前图片压缩的宽度，来减少生成的图片看不清的情况，如何判断手机像素(30万，50万，60万，80万，100万，200万，500万，800万，1400万。。。)，如何判断手机拍照方向（正着拍的照片肯定小于反着拍的图片大小，但是遇到图片长和宽相同的就分不出正和反了)，现在还是头疼这些问题，如果有qq那个滚动鼠标设置产看图片%多少的功能就好了

**Comment by think2011** [comment]
@liuqingchi 
关于QQ一样的滚动查看百分比涉及到UI，所以不会考虑做的，以上的听起来能够可以实现一个智能压缩的功能。

**Comment by liuqingchi** [comment]
很倒霉自己挖个坑，跳下去了，前面我在 获得图片的缩放尺寸 resize: function(img) { 函数里面 根据图片的宽度或者高度 设置 默认生成图片的宽度，没想到这么一弄，今天才发现一个问题，就是用苹果手机上传的图片传到服务器上成了，大半个黑色+一点扁的图片，应该是苹果上传的图片经过 调整正确的拍摄方向，造成的。好多图片得重传了。

**Comment by liuqingchi** [comment]
其实我也没做什么啊，只是根据图片的宽度来判断 一下应该设置生成图片的宽度而已啊，而且android和pc下的图片好像没有 调整正确的拍摄方向 的功能 啊

**Comment by liuqingchi** [comment]
最主要的是iphone5s拍出来的图片那样，iphone6+正常

**Comment by think2011** [comment]
恩，PC 和 android的不需要调整旋转（自动处理了）。

通过设置最低宽度or高度&质量来解决吧。
