### ISSUE TITLE
建议对图片压缩后尺寸做一下智能处理

### ISSUE THREAD

**Issue by yangliujie** [think2011/localResizeIMG3#2]
亲，
用了一下你的第三版的本地压缩代码，相当不错，比plupload要小巧的多，但对于图片尺寸处理不是很理想，存在两个问题。
1. 如指定的宽/高大于实际图片大小，会导致图片被拉大。
2. 如同时指定宽高，可能会导致图片变形，建议按最短边进行宽高比锁定压缩。  

建议针对这两个问题做一下优化，那就比较完美了。  
resize: function (img) {
            var w = this.defaults.width,
                h = this.defaults.height,
                scale = img.width / img.height,
                ret = {w: img.width, h: img.height};

            if (w & h) {
                ret.w = w;
                ret.h = h;
            }
            else if (w) {
                ret.w = w;
                ret.h = Math.ceil(w / scale);
            }

            else if (h) {
                ret.w = Math.ceil(h * scale);
                ret.h = h;
            }

            return ret;
        }

**Comment by think2011** [comment]
谢谢，会找个时间处理的。

**Comment by think2011** [comment]
Hi，考虑过后决定不再修改了。
1. 超出宽高，压缩容量比没压缩之前还要高，就失去了压缩的必要了。
2. 如果指定宽高，确实会变形，因为已经处理了宽/高自适应，如果指定宽高也适应的，感觉没有必要。

**Comment by yangliujie** [comment]
Hi，考虑过后决定不再修改了。
 1. 超出宽高，压缩容量比没压缩之前还要高，就失去了压缩的必要了。

这里做一下判断，如果指定宽高大于图片实际宽高，那么就不压缩了，防止图片被拉大。
