### ISSUE TITLE
找到支持图片路径的方法

### ISSUE THREAD

**Issue by fengqiaoguke** [think2011/localResizeIMG3#20]
我之前提过几次问题,因为我是用插件调用原生摄像头,然后获取图片路径.
现在我看了下你们的代码,稍微修改下,就可以通过传图片路径压缩了,不用非得input表单了.所以你们能否把这个插件做的更灵活点.
![qq 20150403223117](https://cloud.githubusercontent.com/assets/2267487/6983504/50dd2b30-da51-11e4-8930-2612c83190c4.png)

问题补充：照片自动旋转没有生效

**Comment by think2011** [comment]
@fengqiaoguke  (已更新版本)[https://github.com/think2011/localResizeIMG3/releases]

**Comment by think2011** [comment]
图片旋转没有生效的原因可能是，图片本身没有记录EXIF信息或者在传入之前就丢失了EXIF信息

**Comment by zhipenglin** [comment]
读了下您的代码，貌似判断了只有IOS设备才用EXIF获取信息

**Comment by think2011** [comment]
@zhipenglin 仅android没有处理EXIF信息（本身就处理了），其他情况都有处理的，或许图片没有旋转的原因处在别的地方？
