### ISSUE TITLE
为什么android手机压缩出来的图片还是很大呢？

### ISSUE THREAD

**Issue by luxinxian** [think2011/localResizeIMG3#22]
发现一个问题3.0.19版本，华为荣耀6，android 4.4.2 浏览器UC v-10.3 压缩一张2M的JPG，设定相同的尺寸和质量后用pc chrome浏览器执行压缩结果是20K左右，但android手机执行时压缩结果是200K左右，iOS压缩也是20K属正常。。  为什么呢？

现在网上提供的二维码进入的那个demo就有这个问题：）

**Comment by think2011** [comment]
@luxinxian  你可以试试android自带的浏览器，用朋友的小米4测试没有问题。
还是那句话，目前没有合适的设备去测试，一旦有机会有时间会尽量处理。
之后会增加版本号调试方面的处理。

**Comment by bobo183** [comment]
拍照上传的时候，压缩很慢

**Comment by think2011** [comment]
@bobo183  经测试，发现某些浏览器压缩很慢，跟前端无关，无解。
