### ISSUE TITLE
IPHONE 5S 上传后显示被压缩黑屏

### ISSUE THREAD

**Issue by qiqilie** [think2011/localResizeIMG3#24]
IPHONE 5S 上传后显示被压缩黑屏，只显示了小部分图片，大部分图片被压缩，超过1M以上会出现这个问题，pc版好像没问题，拍照以后还容易出现闪退情况
![wawawa](https://cloud.githubusercontent.com/assets/11782062/7038002/d53c4da4-dddd-11e4-9c08-6c7a851b463f.PNG)

**Comment by liuqingchi** [comment]
我遇到的是同样的问题，iphone5s上传照片有问题，不过localResizeIMG 是没有问题的
![20150410200722](https://cloud.githubusercontent.com/assets/346580/7087367/4412c948-dfbd-11e4-9f7f-c3539905c5f1.png)

**Comment by liuqingchi** [comment]
问题已经找到，不找到问题所在郁闷，找到了跟郁闷，你什么时候把原来exif.js 文件下面渲染ios6 里面图片大于1M的问题的代码去掉了，这段代码也可以解决苹果拍的图片旋转问题，所以我就把以前你写的代码把现在判断有没有旋转的替换掉了
                                          var mpImg = new MegaPixImage(img);
						mpImg.render(canvas, {
							width: canvas.width,
							height: canvas.height,
							orientation: EXIF.getTag(this, "Orientation")
						});
这样问题就解决了，但是也不知最近跟新的代码哪里有问题，上传速度就是没有3月份的代码快，所以每次解决掉问题以后，我还得把原来的代码找到替换上去。
还有就是我新下载的localResizeIMG3把原来的38kb的exif.js文件替换后，解决了iphone5s的问题，但是android手机上传图片返回时就变成白色的(这个图片是我用php在后台压缩后的缩略图)，但是上传的js压缩的图片是成功的，不过后来我把所有的js文件都用原来的3月份的替换掉就解决了，而且如上所述，速度也提升了。

**Comment by qiqilie** [comment]
能给我发个已经解决的版本到邮箱吗？谢谢，75612743@qq.com

**Comment by qiqilie** [comment]
我试了下你说的这段代码可以解决苹果拍的图片旋转问题，没有起到作用，是什么问题？

**Comment by think2011** [comment]
@liuqingchi 非常感谢，之所以去掉是因为发现有问题，在iphone4 & iphone4s下压缩会有问题。
IOS8不需要用到MegaPixImage，以为IOS7也没问题了。

择日修复。

**Comment by liyahui** [comment]
@think2011 你好 5s的问题修复了吗

**Comment by think2011** [comment]
@liuqingchi  据说高于IOS7.12的版本无此问题，在考虑修不修复。

**Comment by qiqilie** [comment]
如果可以修复建议最好修复下，因为不能保证每个人手机都是7.12版本以上的啊，而且还有很多越狱的版本，基本都是没有升级的

**Comment by xFairs** [comment]
啥时候修复？

**Comment by devilmengcry** [comment]
同求兼容7.1.2的，谢谢。84368145@qq.com

**Comment by Megic** [comment]
同求发一下我的邮箱吧。420636220@qq.com

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG3/releases)

**Comment by devilmengcry** [comment]
3.1.1 iphone5 ios7.1，显示被压缩

**Comment by think2011** [comment]
@devilmengcry  线上debug测试的吗？

**Comment by devilmengcry** [comment]
包下下来，原封不动传自己服务器上测的。

**Comment by think2011** [comment]
@devilmengcry 请用线上debug核实一下，线上debug有清除缓存的。

**Comment by devilmengcry** [comment]
@think2011 开了debug，iphone5 ios7.1问题还在。

**Comment by think2011** [comment]
@devilmengcry  恩，我下载个ios7 模拟器测试一下。

**Comment by devilmengcry** [comment]
@think2011 辛苦了，还是要谢谢作者。

**Comment by think2011** [comment]
![](http://s1.momo.moda/2015/05/14/85422afb467e9456013a2a51d4dff702.png)

@devilmengcry  IOS8和IOS7都测试了，问题解决了，已更新版本。
