### ISSUE TITLE
关于base64编码的图片上传到c#的处理

### ISSUE THREAD

**Issue by tophome** [think2011/localResizeIMG3#25]
你好，我服务器端是基于.net进行开发的。

我想问下，base64编码是通用的吗？

我进行转换是提示如下错误，今天网上查了一天，也没找到方法，不知道您对这方便是否了解，谢谢。
The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or a non-white space character among the padding characters.

**Comment by qiqilie** [comment]
是我的也遇到这个问题，3代里面获取的值里面多了一段前缀data:image/jpeg;base64，1代里面是没有的因为用的是result.clearBase64方法。建议3代里面也加上这个方法。
我解决方法是把这段前缀用程序替换掉就行，代码如下：
base64 = base64.Replace("data:image/jpeg;base64,", "");

**Comment by think2011** [comment]
@qiqilie 带前缀的才是base64的真面目，现在的版本之所以加上是优化内存的占用的原因。

**Comment by qiqilie** [comment]
但是这个解析出来的数据保存后会有问题，能帮忙看下5S图片上传被压缩的问题吗？还有1代里面是否可以优化下，IPHONE里面上传不能自动翻转图片
