### ISSUE TITLE
压缩后的图片是base64的，我想把它还原成二进制的图片文件，然后再上传，咋搞？

### ISSUE THREAD

**Issue by liaosimin** [think2011/localResizeIMG3#29]
我要上传到七牛云，它提供的接口只有普通的文件格式，传base64会出错。而且base64的文件比二进制文件大1/3，浪费手机流量。

**Comment by think2011** [comment]
同样的大小，base64要比原件大0.8。
我不明白你说的二进制是什么意思，如果是想要转换成常规的模式上传（input:file from submit），似乎 FileReader 这个接口能够帮到你把base64转换成文件的形式上传，但生成的base64已经是确定的大小了，不会再减少了。
