### ISSUE TITLE
图片上传显示一半

### ISSUE THREAD

**Issue by zhangtxcong126** [think2011/localResizeIMG3#3]
测试了几个手机，很多图片，压缩后，图片显示一半，直接在你的demo里面测试的，传到你服务器去了吧，看的到不，大神，两个女生的图片

**Comment by think2011** [comment]
服务器没有保存图片的。
请告知一下手机型号 和 上传一下有问题的图片吧，才能定位问题。

**Comment by zhangtxcong126** [comment]
是用IPHONE4S拍的，把图片发到电脑或者是其它手机上，再传就是好的，直接上传就是这样的，IPHONE4S的其它图片都正常，就这几张不正常
![1](https://cloud.githubusercontent.com/assets/11205105/6387346/dda2bd9a-bdc4-11e4-956a-78aa2596bb50.jpg)
![2](https://cloud.githubusercontent.com/assets/11205105/6387347/dda2db04-bdc4-11e4-9559-25258d697f33.jpg)

**Comment by zhangtxcong126** [comment]
我看到这个是用的IPHONE4S的“正方形”拍的，有长方形等等其它一些选项。不好意思啊，大神，刚才搞这个图片，耽误这么久

**Comment by think2011** [comment]
恩，之前有朋友提到过这个问题，在 iphone4s 上面。
拍摄几张图片传到电脑上测试发现却无法重现，有可能是手机本身的处理需要作调整。

找个机会处理一下。

**Comment by zhangtxcong126** [comment]
嗯，那我就期待修复了，你发明的这个东西很好，赞啊，谢谢分享

**Comment by laomoi** [comment]
很容易遇到这个问题， 麻烦您自己试试看， 我用iphone5s 上传了一张相册照片，原始图片 3264x2448， 客户端预压成 300x400的图片时， 高度是对的，图片左边一半是黑色一片， 右边一半则是图片被压扁成了一半宽度。

简单来讲就是类似于 scaleX = 0.5, scaleY =1 的这种效果，

**Comment by laomoi** [comment]
不管是拍照还是从相册中选取，iphone5s这个问题是必现的。。麻烦作者找时间看一下。。最近还是挺需要您这个插件功能的。

**Comment by think2011** [comment]
@laomoi  @zhangtxcong126 
我的iphone5用4个方向测试都没有问题，怀疑可能是 设备 或者 旋转代码的原因。

下午打算修复问题，能否加下我的QQ，发送几张有问题的原图让我调试一下。

我的QQ号码是 452125301

**Comment by think2011** [comment]
@zhangtxcong126  @laomoi   已经更新版本，有空试试吧。
