### ISSUE TITLE
不设置width，获取base64不正确

### ISSUE THREAD

**Issue by liulu081227** [think2011/localResizeIMG3#38]
经测试，options参数不设置width的情况下，以下操作获取base64不正确：
1、拍照上传
2、选择iphone拍出来的照片

测试手机：ios5s、ios6、小米Note、其它安卓手机

请问是什么问题？

**Comment by think2011** [comment]
我用线上demo测试（chrome修改js，不传第二个参数），没能重现你说的问题。

理论上线上demo预览图片能出现，base64就算是生成成功的了，因为预览的src就是base64。

**Comment by liulu081227** [comment]
你好，我这里用手机测试，拍照上传不行，或者测试iphone时在图库里选以前拍的照片也不行

这是设置了width的测试结果：
![7 pic](https://cloud.githubusercontent.com/assets/6356869/7628749/96e4cc78-fa59-11e4-98b8-4aa8ed070231.jpg)
![6 pic](https://cloud.githubusercontent.com/assets/6356869/7628753/9dafb266-fa59-11e4-887a-447178a59333.jpg)

这是没有设置了width的测试结果：
![8 pic](https://cloud.githubusercontent.com/assets/6356869/7628760/ae4bb80e-fa59-11e4-9410-0e3b716420f1.jpg)
base64:data:,

**Comment by liulu081227** [comment]
我把iphone拍的照片传到电脑上，用pc测试，压缩图片宽高掉个，旋转了90度，在手机上测试不行

**Comment by think2011** [comment]
> 压缩图片宽高掉个，旋转了90度

这句话没弄明白意思。
实测IOS7存在这个问题，IOS8不会，找个时间修复一下。

**Comment by liulu081227** [comment]
@think2011  就是原图3264*2468，压缩后2468*3264

**Comment by think2011** [comment]
@liulu081227  更不明白了...

**Comment by liulu081227** [comment]
![qq20150514-1 2x](https://cloud.githubusercontent.com/assets/6356869/7629484/8458142e-fa5f-11e4-975d-d01ceb507dbf.png)
![qq20150514-2 2x](https://cloud.githubusercontent.com/assets/6356869/7629486/89bec8a4-fa5f-11e4-9940-3c2bfa946a92.png)

**Comment by think2011** [comment]
@liulu081227  因为将图片旋转成拍摄时的方向了，这个方向是对的吗？

**Comment by think2011** [comment]
具体原因没有找到，但是发现 3264 x 2448 这个尺寸就会出错，所以宽度 or 高度超出范围，则 * 0.8来解决。

下次重构优化时找找原因。

已发布新版本

**Comment by think2011** [comment]
close #38

**Comment by liulu081227** [comment]
旋转后的方向是对的，谢谢回答！
