### ISSUE TITLE
新版直接报错

### ISSUE THREAD

**Issue by bobo183** [think2011/localResizeIMG3#39]
新版移动端上传直接报错……

**Comment by think2011** [comment]
所以你还得告诉我是什么错，用的什么设备和系统版本..

因为我测试大多数情况是通过的。

**Comment by liugu** [comment]
怎么批量上传图片？

**Comment by KKzcp** [comment]
小米4手机，引用lrz.mobile.min.js通过QQ浏览器和UC浏览器分别上传同一张图片（45.1KB），压缩质量0.5;
QQ最终得到的图片是279KB，UC得到的图片是20.1KB，为什么呢？？

**Comment by think2011** [comment]
@liugu 大概你可以遍历文件组，然后挨个执行lrz。

**Comment by bobo183** [comment]
AMD模式加载
