### ISSUE TITLE
iphone4s在微信浏览器里拍照上传偶尔闪退

### ISSUE THREAD

**Issue by bigsalen** [think2011/localResizeIMG3#4]
非常高兴看到有新版本出来，经IPHONE4S单一测试，发现在微信浏览器中拍照上传出现闪退现象，整个微信都崩溃退出了，不知道是什么原因，概率大概在30%左右。从相册选择已拍摄照片上传没出现该问题。（我的IPHONE4S是16G的，剩余内存大概1.7G）

**Comment by think2011** [comment]
iphone4s的运行内存是512m的，很遗憾，目前没有此设备测试... 
如果是内存问题，只能想办法优化内存占用了。
