### ISSUE TITLE
IE 11 报错

### ISSUE THREAD

**Issue by SitanHuang** [think2011/localResizeIMG3#40]
![qq](https://cloud.githubusercontent.com/assets/8856350/7672424/38f85256-fca7-11e4-93fd-4061e5be6b3a.png)
不是IE内核的浏览器都可以
我也引入了类库
lrz.mobile.min.js和
lrz.pc.min.js

请问是什么问题？

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG3/releases)

**Comment by SitanHuang** [comment]
谢谢，有空来拉斯维加斯的时候，来我家做客，我12岁，刚开始web开发，QQ: 978494543
