### ISSUE TITLE
原图片分辨率小于目标分辨率的时候，图像被拉伸

### ISSUE THREAD

**Issue by yourlin** [think2011/localResizeIMG3#42]
这样貌似不合理吧？

**Comment by think2011** [comment]
不太明白你的意思，能举个例子吗？

**Comment by smilecoder** [comment]
图片是300x300,设置了宽度400
图片变成了400x400,
希望>400,才做处理。

**Comment by dwandw** [comment]
已经解决

**Comment by moxuanyuan** [comment]
@dwandw 看了代码，好似没有完全解决问题。。。你只是处理了同时设有width、height的情况，单设width或者height，还是会有问题

**Comment by dwandw** [comment]
@moxuanyuan 已修复
