### ISSUE TITLE
安卓机QQ浏览器压缩图片 大小变大

### ISSUE THREAD

**Issue by KKzcp** [think2011/localResizeIMG3#45]
小米4手机，Android版本4.4.4，python开发的接收服务端，通过QQ内置浏览器上传一张45.6KB的JPG，压缩后得到的大小为279KB，同样的压缩参数下上传同一张JPG，UC浏览器上传压缩结果为20.1KB,chrome浏览器上传压缩结果为13.4KB，为什么？？？

**Comment by think2011** [comment]
低版本的android实际上压缩输出的是PNG的格式，或许你用的是旧版本的lrz，新版本已经判断 < 4.5会使用算法压缩来解决。

**Comment by think2011** [comment]
低版本的android实际上压缩输出的是PNG的格式，或许你用的是旧版本的lrz，新版本已经判断 < 4.5会使用算法压缩来解决。
