### ISSUE TITLE
ios 7.1.1图片挤压问题

### ISSUE THREAD

**Issue by tianwing** [think2011/localResizeIMG3#49]
ios 7.1.1上传图片的时候，还是有图片挤压的问题。ios7.1.2没有问题了。

**Comment by 280213753** [comment]
我也有这个问题，怎么解决啊？

**Comment by qianshankun** [comment]
我也有这个问题，希望帮忙给解决下

**Comment by think2011** [comment]
@qianshankun  @tianwing  恩，用模拟IOS7是测试通过的，得找个设备测试才能知道。

**Comment by qianshankun** [comment]
你部署到外网。我来做测试，可否？

**Comment by qianshankun** [comment]
QQ群252799167 ,好几个人 都希望你解决下问题。

**Comment by think2011** [comment]
@qianshankun 估计可以用 browser-sync 来同步调试，但是我没有时间，

ps: 几天前看到这个信息，今早才回的是因为木有时间，分散精力做不好事情。

**Comment by think2011** [comment]
https://github.com/stomita/ios-imagefile-megapixel  

这个是用于修改IOS8以下问题，你可以测试以下，如果这个能行的话，就100%可以说明问题出在lrz3上了。

如果你找到问题了，可以提个PR上来。

@qianshankun

**Comment by qianshankun** [comment]
好的。谢谢了。 我回头找时间研究下。

**Comment by fengqiaoguke** [comment]
个别ios照片挤压很严重,请看这里 http://ask.dcloud.net.cn/question/5682

**Comment by fengqiaoguke** [comment]
我再报一个bug：手机拍照，有时候照片会横着，你们虽然修复了。但有个问题，如果设置了图片宽度，你们是先裁剪到指定宽度，然后再翻转（比如我设置width：500，结果是高度是500，宽度是375）看这个图片：http://app-img.fengqiaoju.com/user/1/1/blog/d8489ff60db12312000d9da7291b167e.jpeg 右键看属性

**Comment by dwandw** [comment]
已经解决
