### ISSUE TITLE
在线演示页，IPHON及安卓手机大图片都压缩不了

### ISSUE THREAD

**Issue by bendigg** [think2011/localResizeIMG3#51]
如题，在线演示页图片上传不了。
下到本地，大图片也上传不了，只有小图片可以上传。
大图片提示如下：
TypeError: Argument 1 is not valid for any of the 2-argument overloads of URL.createObjectURL.
img.src = typeof src === 'string' ? src : URL.createObjectURL(src);
或者错误如下
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
var result = JSON.parse(xhr.response);

JS编写如下
(function () {
    var input = document.querySelector('input');

    input.onchange = function () {
        // 也可以传入图片路径：lrz('../demo.jpg', ...
        lrz(this.files[0], {
            before: function() {
                console.log('压缩开始');
            },
            fail: function(err) {
                console.error(err);
            },
            always: function() {
                console.log('压缩结束');
            },
            done: function (results) {
            // 你需要的数据都在这里，可以以字符串的形式传送base64给服务端转存为图片。
            console.log(results);

            // 以下为演示用内容
            var tip = document.querySelector('#tip'),
                report = document.querySelector('#report'),
                footer = document.querySelector('footer');

            report.innerHTML = footer.innerHTML =  '';
            tip.innerHTML = '<p>正在生成和上传..</p>';
            demo_report('原始图片', results.origin, results.origin.size);

            setTimeout(function () {
                //demo_report('客户端预压的图片', results.base64, results.base64.length * 0.8);

                // 发送到后端
                var xhr = new XMLHttpRequest();
                var data = {
                    base64: results.base64,
                    size: results.base64.length // 校验用，防止未完整接收
                };

                xhr.open('POST', 'upload.php');
                xhr.setRequestHeader('Content-Type', 'application/json; charset=utf-8');
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === 4 && xhr.status === 200) {
                        var result = JSON.parse(xhr.response);

                        result.error
                            ? alert('服务端错误，未能保存图片')
                            : demo_report('服务端实存的图片', result.src, result.size);

                        tip.innerHTML = '<p>生成和上传完毕</p>';
                    }
                };

                xhr.send(JSON.stringify(data)); // 发送base64
            }, 100);
            }
        });
    };

    /**
     * 演示报告
     * @param title
     * @param src
     * @param size
     */
    function demo_report(title, src, size) {
        var img = new Image(),
            li = document.createElement('li'),
            size = (size / 1024).toFixed(2) + 'KB';

        if(size === 'NaNKB') size = '';

        img.onload = function () {
            var content = '<ul>' +
                '<li>' + title + '（' + img.width + ' X ' + img.height + '）</li>' +
                '<li class="text-cyan">' + size + '</li>' +
                '</ul>';

            li.className = 'item';
            li.innerHTML = content;
            li.appendChild(img);
            document.querySelector('#report').appendChild(li);
        };

        img.src = typeof src === 'string' ? src : URL.createObjectURL(src);
    }

    // 演示用服务器太慢，做个延缓加载
    window.onload = function () {
        input.style.display = 'block';
    }
})();

PHP编写如下：
<?php
$run_id=$_REQUEST['run_id'];
$sclx=$_REQUEST['sclx'];
$sclx_key=$sclx."_key";
$base64=file_get_contents("php://input"); //获取输入流
$base64=json_decode($base64,1);
$data = $base64['base64'];
preg_match("/data:image\/(.*);base64,/",$data,$res);
$ext = $res[1];
if(!in_array($ext,array("jpg","jpeg","pjpeg","png","gif","bmp"))){
	echo json_encode(array("error"=>$ext));die;
}
$file=time().'.'.$ext;
$file2="tmp/".time().'.'.$ext;
$data = preg_replace("/data:image\/(.*);base64,/","",$data);
$ress = file_put_contents($file2,base64_decode($data));
if ($ress) {
	$size=filesize($file2);
	echo json_encode(array("size"=>$size,"src"=>$file2));
}else{
	echo json_encode(array("size"=>0,"src"=>""));
}
?>

**Comment by think2011** [comment]
Hi,请发一张图片原件到我的邮箱吧，我的邮箱是 452125301@qq.com

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG4)
