### ISSUE TITLE
用作批量压缩图片的问题。

### ISSUE THREAD

**Issue by ChanJoseph** [think2011/localResizeIMG3#52]
我用于产品图片压缩，让用户看到的图片不那么大，加载速度快一点。

就是每次刷新页面时，将每个产品的图片都调用那个方法压缩一次。
发现当产品比较多时，即使是异步处理，也会给网页带来巨大负担：表现为，在加载页面时，不断循环调用函数，因为调用次数过多，页面会卡顿，加载的前几秒网页会根本动不了。

请问题主或其他朋友有没有其他办法进行压缩图片？（不用缩略图路径的方式）

**Comment by think2011** [comment]
恩，一直在考虑重构，这个需求是个很好的重构点，重构大概会在1 2个月后吧.. 得找个时间做..

**Comment by qianshankun** [comment]
ios 7.1.1图片挤压问题   能帮忙解决下吗？

**Comment by dwandw** [comment]
这个压缩图片应该在服务器端生成好的吧 都在前端处理必须卡呀

**Comment by dwandw** [comment]
@qianshankun ios 7.1.1图片挤压问题 已经解决

**Comment by qianshankun** [comment]
和作者联系下搞上去，共享下。

**Comment by qianshankun** [comment]
@ dwandw 和作者联系下搞上去，共享下。

**Comment by dwandw** [comment]
@qianshankun https://github.com/dwandw/localResizeIMG3 先用这里的吧

**Comment by dwandw** [comment]
@qianshankun 作者已经合并了 可以用了

**Comment by qianshankun** [comment]
@ dwandw 好的，了解了。谢谢你们了。
