### ISSUE TITLE
拍照时候，修复方向以后，图片宽度不对

### ISSUE THREAD

**Issue by fengqiaoguke** [think2011/localResizeIMG3#53]
手机拍照，有时候照片会90度横着，你们虽然修复了照片方向问题。但有个问题，如果设置了图片宽度，你们是先裁剪到指定宽度，然后再翻转（比如我设置width：500 ，结果是是375x500，正确应该是500x375）看这个图片是ios下拍照的：http://app-img.fengqiaoju.com/user/1/1/blog/d8489ff60db12312000d9da7291b167e.jpeg 右键看属性宽高。不知道我描述的清楚不，我qq 564069448

**Comment by dwandw** [comment]
已经解决
