### ISSUE TITLE
在线演示手机端没效果

### ISSUE THREAD

**Issue by amourz** [think2011/localResizeIMG3#54]
pc端没问题，手机上测试没出来效果，测试手机是小米红米，用的uc浏览器

**Comment by amourz** [comment]
用手机opera可以，应该是uc内核不支持吧

**Comment by fangge** [comment]
小米的MIUI6，比如红米、小米note下选择图库上传图片无法显示出来，也就是一直停留在上传中

**Comment by xuz0917** [comment]
我也遇到了

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG4)
