### ISSUE TITLE
加上option后没有回调了，求解

### ISSUE THREAD

**Issue by dancinglone** [think2011/localResizeIMG3#59]
直接上代码 ：
function img_compress(img) {
		lrz(img,{quality:0.2}, {
		 	before: function() {
                console.log('压缩开始');
	        },
	        fail: function(err) {
	            console.error(err);
	        },
	        always: function() {
	            console.log('压缩结束');
	        },
	        done: function (results) {
	        	console.log(results);
	        	console.log('压缩完成了');
	        }
    	});
	};

去掉{quality:0.2}则可以正常回调，求解，感谢！

**Comment by robert0001** [comment]
作者给的示例代码中有问题，option和function是应该放在一起的，像这样：

function img_compress(img) {
lrz(img,{quality:0.2,
before: function() {
console.log('压缩开始');
},
fail: function(err) {
console.error(err);
},
always: function() {
console.log('压缩结束');
},
done: function (results) {
console.log(results);
console.log('压缩完成了');
}
});
};

希望作者能够修改一下
