### ISSUE TITLE
你这用的是HTML5上传图片，用html5plus+，直接调用手机的像机，好像不行。

### ISSUE THREAD

**Issue by saymy** [think2011/localResizeIMG3#6]
如题，出现如下错误。
Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided. at js/localResizeIMG/lrz.mobile.min.js:3

**Comment by think2011** [comment]
@saymy 
请用说明中的例子试试吧，已更新版本。

p.s: iphone 6 puls， IOS8 实测无误。
