### ISSUE TITLE
图片背景是透明的时候，压缩以后变成白色

### ISSUE THREAD

**Issue by weer0026** [think2011/localResizeIMG3#65]
rt

**Comment by cdll** [comment]
表示没遇到过~

**Comment by yuxiaolei1989** [comment]
![image](https://cloud.githubusercontent.com/assets/7732447/8870871/dc00925e-3223-11e5-8e39-c7a7bfbab71f.png)
有添加白色背景

**Comment by moxuanyuan** [comment]
将 ctx.fillStyle = 'rgba(0, 0, 0, 0)' 则可以了

**Comment by think2011** [comment]
因为压缩后的格式是JPG，而JPG不支持透明背景，如果不加白色，那么背景会是黑色的。
