### ISSUE TITLE
为什么在安卓手机和苹果手机里，上传多张图片，就会闪退

### ISSUE THREAD

**Issue by ihadai** [think2011/localResizeIMG3#66]
插件很好用，非常感谢作者。
 但是经过一段时间使用，在安卓手机和苹果手机里，上传多张图片，就会闪退。 我是在微信里打开的网页。  是不是有什么优化手机占用内存的方法。 请赐教。

**Comment by think2011** [comment]
[已更新版本](https://github.com/think2011/localResizeIMG4)

**Comment by ihadai** [comment]
好的，谢谢楼主，我试试。
